### ISSUE TITLE
Not able to compile adb file

### ISSUE THREAD

**Issue by deepakkapoor624** [gutschke/adb-fastboot#1]
HI,
Can you please tell me the process for compiling of adb and fastboot so they can be run on arm Processor.
As running the executable file on arm platform throws an error.

**Comment by gutschke** [comment]
You need a Linux build environment. Then you should download
   git clone https://android.googlesource.com/platform/system/core platform_system_core
   git clone https://android.googlesource.com/platform/system/extras platform_system_extras
   git clone https://android.googlesource.com/platform/external/f2fs_tools platform_external_f2fs_tools

Apply the adb-fastboot.diff file to "platform_system_core". Afterwards, you should be able to enter both the "adb" and the "fastboot" directories and successfully excecute "make all". If you encounter errors, you probably are missing built dependencies. Figure out what you are missing and install the necessary tools or header and library files. I can't really help you there, as that depends on the specifics of your build environment.

The Makefiles are a little bit of a quick hack though. You should run "make clean" before you change directories in order to build the other binary. A "dirty" adb directory can prevent fastboot from being built.

If you are building against glibc, your target run-time environment will need to have the same dynamic libraries as your build environment. If you build against ulibc or bionic, you might or might not be able to link statically. I haven't tested that.
