### ISSUE TITLE
crypto_utils/android_pubkey.h error

### ISSUE THREAD

**Issue by THS-on** [gutschke/adb-fastboot#2]
Hello,
I'm trying to build the latest master with your patch (only adb) because I need the latest adb Version in Debian on i686. Your provided builds are working fine but when my builds fail with following message:

``` adb_auth_host.cpp
adb_auth_host.cpp:42:41: schwerwiegender Fehler: crypto_utils/android_pubkey.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.
Makefile:59: die Regel für Ziel „.build/adb_auth_host.o“ scheiterte
make: *** [.build/adb_auth_host.o] Fehler 1 
```

Is there a way to fix this?

Thanks,
THS-on

**Comment by gutschke** [comment]
Try again now and let me know what happens.

I updated the patch to work with newer versions of the Android sources. But
I am not 100% sure that the changes to android_pubkey.c are actually
correct. Please test and report back.

Alternatively, compile against BoringSSL instead of OpenSSL; then you don't
need to modify android_pubkey.c. Unfortunately, BoringSSL isn't readily
available for all Linux distributions just yet.

**Comment by THS-on** [comment]
I have compiled adb successfully on Debian jessie this morning.
I created a sym link to use adb with the newest version of Android Studio and it's working fine. I can use all the functionalities I need. I've not tried to compile fastboot.

I've compiled against libssl1.0.0 and had no issues.
Thank you for your quick response and fix,
THS-on
